name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version number'
        required: true
        default: '0.0.10'

jobs:
  echo_version:
    runs-on: windows-2019
    steps:
      - run: |
          echo "Version: ${{ github.event.inputs.version }}!"
