name: manually-triggered-workflow

on: workflow_dispatch

jobs:
  say_version:
    runs-on: windows-2019
    steps: 
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        run: |
          echo "Hello ${{ github.ref }}!"
          echo "${{ github.ref_name }}"
          echo "${{ github.run_number }}"
